# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DatasetSimple

    DatasetSimple(;
        name=nothing,
        description=nothing,
        group=nothing,
        sequence=nothing,
    )
The fuction gives a dataset given a group, a sequence,an input and a description 

# Arguments
    - name::String
    - description::String
    - group::String
    - sequence::Int64
# Return 
The function returns a new dataset
"""
Base.@kwdef mutable struct DatasetSimple <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    group::Union{Nothing, String} = nothing
    sequence::Union{Nothing, Int64} = nothing

    function DatasetSimple(name, description, group, sequence, )
        OpenAPI.validate_property(DatasetSimple, Symbol("name"), name)
        OpenAPI.validate_property(DatasetSimple, Symbol("description"), description)
        OpenAPI.validate_property(DatasetSimple, Symbol("group"), group)
        OpenAPI.validate_property(DatasetSimple, Symbol("sequence"), sequence)
        return new(name, description, group, sequence, )
    end
end # type DatasetSimple

const _property_types_DatasetSimple = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("description")=>"String", Symbol("group")=>"String", Symbol("sequence")=>"Int64", )
OpenAPI.property_type(::Type{ DatasetSimple }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DatasetSimple[name]))}

function check_required(o::DatasetSimple)
    true
end

function OpenAPI.validate_property(::Type{ DatasetSimple }, name::Symbol, val)
end
