# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TimeSeriesTableFull_timeSeries_inner

    TimeSeriesTableFullTimeSeriesInner(;
        name=nothing,
        description=nothing,
        sequence=nothing,
    )

  
This function takes as input the name,the description and the sequence of data e and return a new table

# Argument

    - `name::String`
    - `description::String`
    - `sequence::Int64`
# Return

The return is a new table with fixed name and description

"""
Base.@kwdef mutable struct TimeSeriesTableFullTimeSeriesInner <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    sequence::Union{Nothing, Int64} = nothing

    function TimeSeriesTableFullTimeSeriesInner(name, description, sequence, )
        OpenAPI.validate_property(TimeSeriesTableFullTimeSeriesInner, Symbol("name"), name)
        OpenAPI.validate_property(TimeSeriesTableFullTimeSeriesInner, Symbol("description"), description)
        OpenAPI.validate_property(TimeSeriesTableFullTimeSeriesInner, Symbol("sequence"), sequence)
        return new(name, description, sequence, )
    end
end # type TimeSeriesTableFullTimeSeriesInner

const _property_types_TimeSeriesTableFullTimeSeriesInner = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("description")=>"String", Symbol("sequence")=>"Int64", )
OpenAPI.property_type(::Type{ TimeSeriesTableFullTimeSeriesInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TimeSeriesTableFullTimeSeriesInner[name]))}

function check_required(o::TimeSeriesTableFullTimeSeriesInner)
    true
end

function OpenAPI.validate_property(::Type{ TimeSeriesTableFullTimeSeriesInner }, name::Symbol, val)
end
