# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TimeSeriesTableSimple

    TimeSeriesTableSimple(;
        name=nothing,
        description=nothing,
        geographicIntegration=nothing,
        sequence=nothing,
        timeSeries=nothing,
        geogLevels=nothing,
    )

    TODO: Add description
    This fuction 

    # Arguments:

    TODO: Label arguments

    - `name::String`
    - `description::String`
    - `geographicIntegration::String`
    - `sequence::Float32`
    - `timeSeries::Vector{String}`
    - `geogLevels::Vector{String}`

    # Return

    TODO: State what they return
    
    # Example

    TODO: Provide an example

    This function takes as input the name,description, geographic integration, the time series and the geographical level of the data, 
        and returns a table
"""



Base.@kwdef mutable struct TimeSeriesTableSimple <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    geographicIntegration::Union{Nothing, String} = nothing
    sequence::Union{Nothing, Float32} = nothing
    timeSeries::Union{Nothing, Vector{String}} = nothing
    geogLevels::Union{Nothing, Vector{String}} = nothing

    function TimeSeriesTableSimple(name, description, geographicIntegration, sequence, timeSeries, geogLevels, )
        OpenAPI.validate_property(TimeSeriesTableSimple, Symbol("name"), name)
        OpenAPI.validate_property(TimeSeriesTableSimple, Symbol("description"), description)
        OpenAPI.validate_property(TimeSeriesTableSimple, Symbol("geographicIntegration"), geographicIntegration)
        OpenAPI.validate_property(TimeSeriesTableSimple, Symbol("sequence"), sequence)
        OpenAPI.validate_property(TimeSeriesTableSimple, Symbol("timeSeries"), timeSeries)
        OpenAPI.validate_property(TimeSeriesTableSimple, Symbol("geogLevels"), geogLevels)
        return new(name, description, geographicIntegration, sequence, timeSeries, geogLevels, )
    end
end # type TimeSeriesTableSimple

const _property_types_TimeSeriesTableSimple = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("description")=>"String", Symbol("geographicIntegration")=>"String", Symbol("sequence")=>"Float32", Symbol("timeSeries")=>"Vector{String}", Symbol("geogLevels")=>"Vector{String}", )
OpenAPI.property_type(::Type{ TimeSeriesTableSimple }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TimeSeriesTableSimple[name]))}

function check_required(o::TimeSeriesTableSimple)
    true
end

function OpenAPI.validate_property(::Type{ TimeSeriesTableSimple }, name::Symbol, val)
end
