# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


"""
```
TimeSeriesTableFullTimeSeriesInner(;
    name=nothing,
    description=nothing,
    sequence=nothing,
)
```
  
This function creates a reference to an IPUMS Time Series table. 

# Arguments

- `name::String`- **(Optional)** The unique identifier of the time series table.
- `description::String`- **(Optional)** A short description of the time series table.
- `sequence::Int64`- **(Optional)** The order in which the time series table will appear in the metadata API and extracts.

# Returns

This function returns a `TimeSeriesTableFullTimeSeriesInner` object that contains 
information about a desired Time Series table.

# Examples

```julia-repl
julia> IPUMS.TimeSeriesTableFullTimeSeriesInner(name = "1790_cPop",
                                                description =  "1790 Census: Population Data [US, States & Counties]",
                                                sequence = 101)
# Output

{
  "name": "1790_cPop",
  "description": "1790 Census: Population Data [US, States & Counties]",
  "sequence": 101
}
```

# References

Additional information about the `TimeSeriesTableFullTimeSeriesInner`object is available in the [IPUMS Developer Docs](https://developer.ipums.org/docs/v2/workflows/explore_metadata/nhgis/time_series/)
"""
Base.@kwdef mutable struct TimeSeriesTableFullTimeSeriesInner <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    sequence::Union{Nothing, Int64} = nothing

    function TimeSeriesTableFullTimeSeriesInner(name, description, sequence, )
        OpenAPI.validate_property(TimeSeriesTableFullTimeSeriesInner, Symbol("name"), name)
        OpenAPI.validate_property(TimeSeriesTableFullTimeSeriesInner, Symbol("description"), description)
        OpenAPI.validate_property(TimeSeriesTableFullTimeSeriesInner, Symbol("sequence"), sequence)
        return new(name, description, sequence, )
    end
end # type TimeSeriesTableFullTimeSeriesInner

const _property_types_TimeSeriesTableFullTimeSeriesInner = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("description")=>"String", Symbol("sequence")=>"Int64", )
OpenAPI.property_type(::Type{ TimeSeriesTableFullTimeSeriesInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TimeSeriesTableFullTimeSeriesInner[name]))}

function check_required(o::TimeSeriesTableFullTimeSeriesInner)
    true
end

function OpenAPI.validate_property(::Type{ TimeSeriesTableFullTimeSeriesInner }, name::Symbol, val)
end
