# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


"""
```
DatasetFullGeogLevelsInner(;
    name=nothing,
    description=nothing,
    hasGeogExtentSelection=nothing,
)
```
This function gives the geographical information about data

# Arguments
- `name::String`-The dataset identifier 
- `description::String`- A short description of the dataset
- `hasGeogExtentSelection::Bool`- boolean indicating if the dataset has geogrphical extent
# Return 
The function return a new dataset
    
# Example
 OrderedMap { "name": "1790_cPop", "description": "1790 Census: Population Data [US, States & Counties]", "hasGeogExtentSelection": "1"}
# Reference
To find out more about the Dataset type visit the [Reference page of IPUMS API Dataset](https://developer.ipums.org/docs/v2/workflows/explore_metadata/nhgis/datasets/)
"""
Base.@kwdef mutable struct DatasetFullGeogLevelsInner <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    hasGeogExtentSelection::Union{Nothing, Bool} = nothing

    function DatasetFullGeogLevelsInner(name, description, hasGeogExtentSelection, )
        OpenAPI.validate_property(DatasetFullGeogLevelsInner, Symbol("name"), name)
        OpenAPI.validate_property(DatasetFullGeogLevelsInner, Symbol("description"), description)
        OpenAPI.validate_property(DatasetFullGeogLevelsInner, Symbol("hasGeogExtentSelection"), hasGeogExtentSelection)
        return new(name, description, hasGeogExtentSelection, )
    end
end # type DatasetFullGeogLevelsInner

const _property_types_DatasetFullGeogLevelsInner = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("description")=>"String", Symbol("hasGeogExtentSelection")=>"Bool", )
OpenAPI.property_type(::Type{ DatasetFullGeogLevelsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DatasetFullGeogLevelsInner[name]))}

function check_required(o::DatasetFullGeogLevelsInner)
    true
end

function OpenAPI.validate_property(::Type{ DatasetFullGeogLevelsInner }, name::Symbol, val)
end
