# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


"""

```
DataExtract(;
    extractDefinition=nothing,
    number=nothing,
    status=nothing,
    downloadLinks=nothing,
)
```

This function prepares a data extract request for submission to the IPUMS API.

# Arguments

- `extractDefinition::DataExtractDefinition`- **(Optional)** Definition of the extracted data.
- `number::Int64`- **(Optional)** Number of the data.
- `status::String`- **(Optional)** Status of the data extraction (eg. "complete").
- `downloadLinks::DataExtractDownloadLinks`- **(Optional)** Download link for the extracted data.

# Returns

This function returns a `DataExtract` object. 

# Examples

```julia-repl

julia> IPUMS.DataExtract(extractDefinition = IPUMS.DataExtractDefinition(datasets = Dict("1790_cPop" => IPUMS.Dataset(dataTables = ["NT1"],
                                                                        geogLevels = ["place_00498"]),
                                                   "1800_cPop" => IPUMS.Dataset(dataTables = ["NT3"],
                                                                        geogLevels = ["state"])),
                                             timeSeriesTables = Dict("A00" => IPUMS.TimeSeriesTable(geogLevels = ["state"]),
                                                                     "A03" => IPUMS.TimeSeriesTable(geogLevels = ["state"]) ),
                                             dataFormat = "csv_no_header",
                                             timeSeriesTableLayout = "time_by_row_layout",
                                             shapefiles = ["https://api.ipums.org/downloads/nhgis/api/v1/extracts/1234567/nhgis0007_shape.zip"] ,
                                             geographicExtents = ["united states"],
                                             description = "abc",
                                             version = 2,
                                             collection = "nhgis"),
                         number = 2,
                         status = "complete",
                         downloadLinks = IPUMS.DataExtractDownloadLinks(codebookPreview = "https://api.ipums.org/downloads/nhgis/api/v1/extracts/1234567/nhgis0007_csv_PREVIEW.zip",
                                         tableData = "https://api.ipums.org/downloads/nhgis/api/v1/extracts/1234567/nhgis0007_csv.zip",
                                         gisData = "https://api.ipums.org/downloads/nhgis/api/v1/extracts/1234567/nhgis0007_shape.zip")

                        )

# Output

{                                                                                                                                                  
  "extractDefinition": {                                                                                                                           
    "datasets": {                                                                                                                                  
      "1790_cPop": {                                                                                                                               
        "dataTables": [                                                                                                                            
          "NT1"                                                                                                                                    
        ],                                                                                                                                         
        "geogLevels": [                                                                                                                            
          "place_00498"                                                                                                                            
        ]                                                                                                                                          
      },                                                                                                                                           
      "1800_cPop": {                                                                                                                               
        "dataTables": [                                                                                                                            
          "NT3"                                                                                                                                    
        ],                                                                                                                                         
        "geogLevels": [                                                                                                                            
          "state"                                                                                                                                  
        ]                                                                                                                                          
      }
    },
    "timeSeriesTables": {
      "A00": {
        "geogLevels": [
          "state"
        ]
      },
      "A03": {
        "geogLevels": [
          "state"
        ]
     }
    },
    "dataFormat": "csv_no_header",
    "timeSeriesTableLayout": "time_by_row_layout",
    "shapefiles": [
      "https://api.ipums.org/downloads/nhgis/api/v1/extracts/1234567/nhgis0007_shape.zip"
    ],
    "geographicExtents": [
      "united states"
    ],
    "description": "abc",
    "version": 2,
    "collection": "nhgis"
  },
  "number": 2,
  "status": "complete",
  "downloadLinks": {
    "codebookPreview": "https://api.ipums.org/downloads/nhgis/api/v1/extracts/1234567/nhgis0007_csv_PREVIEW.zip",
    "tableData": "https://api.ipums.org/downloads/nhgis/api/v1/extracts/1234567/nhgis0007_csv.zip",
    "gisData": "https://api.ipums.org/downloads/nhgis/api/v1/extracts/1234567/nhgis0007_shape.zip"
  }
}

```
# References

To learn more about the `DataExtract` type, please visit the [IPUMS API DataExtract](https://developer.ipums.org/docs/v2/workflows/create_extracts/microdata)

"""
Base.@kwdef mutable struct DataExtract <: OpenAPI.APIModel
    extractDefinition = nothing # spec type: Union{ Nothing, DataExtractDefinition }
    number::Union{Nothing, Int64} = nothing
    status::Union{Nothing, String} = nothing
    downloadLinks = nothing # spec type: Union{ Nothing, DataExtractDownloadLinks }

    function DataExtract(extractDefinition, number, status, downloadLinks, )
        OpenAPI.validate_property(DataExtract, Symbol("extractDefinition"), extractDefinition)
        OpenAPI.validate_property(DataExtract, Symbol("number"), number)
        OpenAPI.validate_property(DataExtract, Symbol("status"), status)
        OpenAPI.validate_property(DataExtract, Symbol("downloadLinks"), downloadLinks)
        return new(extractDefinition, number, status, downloadLinks, )
    end
end # type DataExtract

const _property_types_DataExtract = Dict{Symbol,String}(Symbol("extractDefinition")=>"DataExtractDefinition", Symbol("number")=>"Int64", Symbol("status")=>"String", Symbol("downloadLinks")=>"DataExtractDownloadLinks", )
OpenAPI.property_type(::Type{ DataExtract }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DataExtract[name]))}

function check_required(o::DataExtract)
    true
end

function OpenAPI.validate_property(::Type{ DataExtract }, name::Symbol, val)
    if name === Symbol("number")
        OpenAPI.validate_param(name, "DataExtract", :format, val, "int64")
    end
end
