module IPUMS

    import Base:
        @kwdef

    using DataFrames
    using Dates
    using HTTP
    using JSON3
    using OpenAPI
    using TimeZones
    using URIs
    using EzXML
    
    include("structs.jl")
    include("constants.jl")
    include("helpers.jl")

    #=
    
    This information was generated by the OpenAPI documentation and 
    subsequently better incorporated into the whole of the package

    =# 

    const API_VERSION = "v2"

    include("modelincludes.jl")
    include("apis/api_DefaultApi.jl")
    include("piracy.jl")
    include("parsers/ddi_parser.jl")

    export DefaultApi
    export parse_ddi
end
