module IPUMS

    import Base:
        @kwdef

    using DataFrames
    using Dates
    using HTTP
    using JSON3
    using OpenAPI
    using OpenAPI.Clients
    import OpenAPI:
        Client
    using TimeZones
    using URIs
    using EzXML
    
    include("structs.jl")
    include("constants.jl")
    include("helpers.jl")

    #=
    
    This information was generated by the OpenAPI documentation and 
    subsequently better incorporated into the whole of the package

    =# 

    const API_VERSION = "v2"

    include("modelincludes.jl")
    include("apis/api_DefaultApi.jl")
    include("piracy.jl")

    #=
        export from_json
        export DataExtract
        export DataExtractDownloadLinks
        export DataExtractExtractDefinition
        export DataExtractPost
        export DataExtractPostResponse
        export DataTableFull
        export DataTableFullVariablesInner
        export DataTableSimple
        export Dataset
        export DatasetFull
        export DatasetFullBreakdowns
        export DatasetFullBreakdownsBreakdownValuesInner
        export DatasetFullGeogLevelsInner
        export DatasetSimple
        export Error
        export Shapefile
        export TimeSeriesTable
        export TimeSeriesTableFull
        export TimeSeriesTableFullTimeSeriesInner
        export TimeSeriesTableSimple
    =# 

    export Client
    export DefaultApi

end
